services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ridei
    environment:
      MYSQL_ROOT_PASSWORD: sasa1234
      MYSQL_DATABASE: db-ridei-app
      MYSQL_USER: ridei_adm
      MYSQL_PASSWORD: sasa1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
