version: '3.8'

services:
    postgres:
      image: postgres:16
      container_name: postgres-ridei
      restart: always
      environment:
        POSTGRES_DB: dbrideiitg
        POSTGRES_USER: db1t6r1d31
        POSTGRES_PASSWORD: 7e7gndo02
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - api-net

volumes:
  postgres_data:

networks:
  api-net:
    driver: bridge