services:
  # Este servicio SOLO se levantará en el VPS
  backend:
    build: .
    container_name: ridei_backend
    restart: always
    ports:
      - "8081:8081" # Expone la API para que Flutter pueda llamarla
    depends_on:
      - db
      - kafka
    environment:
      # Sobrescribimos las variables para que apunten a los contenedores
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ridei_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092