INSERT INTO brands (id, name) VALUES
    (gen_random_uuid(), 'Yamaha'),
    (gen_random_uuid(), 'Honda'),
    (gen_random_uuid(), 'Kawasaki'),
    (gen_random_uuid(), 'Suzuki'),
    (gen_random_uuid(), 'BMW Motorrad'),
    (gen_random_uuid(), 'Ducati'),
    (gen_random_uuid(), 'KTM'),
    (gen_random_uuid(), 'Triumph'),
    (gen_random_uuid(), 'Harley-Davidson'),
    (gen_random_uuid(), 'Aprilia'),
    (gen_random_uuid(), 'MV Agusta'),
    (gen_random_uuid(), 'Husqvarna'),
    (gen_random_uuid(), 'Beta'),
    (gen_random_uuid(), 'GasGas'),
    (gen_random_uuid(), 'Sherco'),
    (gen_random_uuid(), 'Royal Enfield'),
    (gen_random_uuid(), 'Moto Guzzi'),
    (gen_random_uuid(), 'Indian Motorcycle'),
    (gen_random_uuid(), 'Zero Motorcycles'),
    (gen_random_uuid(), 'Energica'),
    (gen_random_uuid(), 'Vespa'),
    (gen_random_uuid(), 'Piaggio'),
    (gen_random_uuid(), 'Kymco'),
    (gen_random_uuid(), 'SYM'),
    (gen_random_uuid(), 'Rieju'),
    (gen_random_uuid(), 'Derbi'),
    (gen_random_uuid(), 'Montesa'),
    (gen_random_uuid(), 'Bultaco'),
    (gen_random_uuid(), 'CFMOTO'),
    (gen_random_uuid(), 'Benelli'),
    (gen_random_uuid(), 'Fantic');
